name: "Twist notification"
description: "GitHub Action to send notifications to Twist using the webhooks API"
inputs:
  message:
    description: "Message to send"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/notify.sh
      shell: bash
      env:
        MESSAGE: "${{ inputs.message }}"
